# Default values for <CHARTNAME>.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1


cron:
  historyLimit: 10
  backoffLimit: 6
  jobs: []
    # Specify the cron jobs here. This is an array of elements that describe a CronJob
    # with a `name`, a `schedule` and `command`
    # Consider the following example to run the 'df' command every 2 minutes
    # - name: listMounts
    #   schedule: "*/2 * * * *"
    #   command: df

image:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
